# Permalinks
#
permalink:           "/:title/"

# Setup
title:               Sang-Kil Park
tagline:             The missing Papers
url:                 http://docs.likejazz.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sang-Kil Park
  url:               http://likejazz.com/
  email:             likejazz@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole

# Custom Gems
gems:
  - jekyll-redirect-from
